/*---------------------------------------------------------------------------------
 * renderer.c -- one-time citro3d/citro2d setup and the per-frame GPU bracket.
 * See renderer.h for the contract this file implements.
 *
 * SETUP SHAPE copied (by convention, not by include path -- see this
 * project's standing rule against depending on sibling projects) from
 * `3ds-project-folder/mc` and `3ds-project-folder/model-making`, both
 * working citro3d projects on this machine:
 *   - render target creation + C3D_FrameBegin(C3D_FRAME_SYNCDRAW) /
 *     C3D_FrameEnd(0) bracket, matching mc's `gfx/screen.c` +
 *     `main.c`'s frame loop and model-making's `main.c`.
 *   - Mtx_PerspTilt + shaderInstanceGetUniformLocation-once-after-bind,
 *     matching model-making's `main.c`.
 * Every byte of this file was typed fresh for dirt2; nothing includes or
 * links against either sibling project.
 *
 * THE ONE SHADER PROGRAM FOR THE WHOLE PROCESS.
 *   `s_shader` (built from dirt2.v.pica, see that file) is created exactly
 *   once, gated by `s_ready`, and freed exactly once, in renderer_shutdown.
 *   It is never rebuilt per frame or per scene. This matters on real
 *   hardware: `mc`'s crackoverlay.c/highlight.c/weatherdraw.c each carry a
 *   comment documenting a use-after-free crash from recreating a
 *   shaderProgram_s mid-session (shaderProgramFree does not null
 *   `vertexShader`, and citro3d separately caches a pointer to the last
 *   bound program) -- this file structurally cannot repeat that mistake
 *   because there is only one call site for shaderProgramInit, guarded by
 *   `s_ready`, for dirt2's entire lifetime.
 *---------------------------------------------------------------------------------*/
#include "render/renderer.h"
#include "core/vecmath.h" /* Vec3/Quat ops, used by renderer_draw_ground's
                              per-vertex lambert shading and
                              renderer_draw_vehicle's box transform below --
                              plain C, no 3DS dependency, so this include is
                              unconditional like renderer.h's own. */

#ifdef __3DS__
#include <3ds.h>
#include <citro3d.h>
#include <citro2d.h>
#include "dirt2_shbin.h" /* generated by picasso from dirt2.v.pica, see the
                             Makefile's existing PICAFILES rule -- no
                             Makefile change needed for this. */

/* Standard devkitPro display-transfer flags for an RGBA8 render target ->
 * RGB8 framebuffer copy, matching both sibling projects' screen setup. */
#define DISPLAY_TRANSFER_FLAGS \
    (GX_TRANSFER_FLIP_VERT(0) | GX_TRANSFER_OUT_TILED(0) | GX_TRANSFER_RAW_COPY(0) | \
     GX_TRANSFER_IN_FORMAT(GX_TRANSFER_FMT_RGBA8) | GX_TRANSFER_OUT_FORMAT(GX_TRANSFER_FMT_RGB8) | \
     GX_TRANSFER_SCALING(GX_TRANSFER_SCALE_NO))

/* Top screen's raw framebuffer is 240x400 in citro3d's coordinate
 * convention (the panel is physically 400x240 landscape; the GPU's tiled
 * memory layout treats it as a rotated 240-wide, 400-tall surface, which is
 * exactly why Mtx_PerspTilt -- not Mtx_Persp -- is used below). */
#define TOP_SCREEN_WIDTH  240
#define TOP_SCREEN_HEIGHT 400

/* Dark slate rather than black so a black debug line is still visible
 * against it; owned entirely by this file, not a supplied asset. */
#define DIRT2_CLEAR_COLOR 0x202030FF

/* Renderer-owned projection constants. renderer_frame_begin's signature is
 * `(const Camera *cam)` -- Camera (see camera.h) carries only smoothed
 * position/target, not FOV/near/far, and that signature is already the one
 * source/main.c calls against (main.c is not this task's file to change).
 * CameraConfig.fov_degrees/near_clip/far_clip therefore aren't reachable
 * from here; these constants are renderer.c's own copy of the same Phase 1
 * placeholder values main.c's CameraConfig uses. If the projection ever
 * needs to be config-driven, renderer.h's signature has to change -- flagged
 * here rather than silently duplicated forever. */
#define DIRT2_FOV_DEGREES 55.0f
#define DIRT2_NEAR_CLIP   0.1f
#define DIRT2_FAR_CLIP    500.0f

static DVLB_s *s_dvlb = NULL;
static shaderProgram_s s_shader;
static bool s_ready = false;

static int s_uloc_projection = -1;
static int s_uloc_modelview = -1;

static C3D_RenderTarget *s_target = NULL;
static C3D_Mtx s_projection;

/* ---------------------------------------------------------------------
 * v0.1 "it drives" gameplay geometry (renderer_draw_ground /
 * renderer_draw_vehicle): flat/vertex-coloured triangles, no textures.
 *
 * Same vertex layout and per-draw-call "rebind everything, one
 * C3D_DrawArrays" convention as debugdraw.c's DebugVertex/s_verts -- kept as
 * a SEPARATE type/buffers here rather than reused from debugdraw.c because
 * debugdraw's are `static` to that translation unit (by design, per its own
 * OWNER note: debugdraw is a self-contained tool, not a shared allocator),
 * and because this geometry needs backface culling ON (see
 * renderer_draw_ground's draw call) while debugdraw's ribbons need it OFF
 * (see debugdraw.c's header comment) -- two different cull states bracketing
 * two different buffers is simpler to get right than one shared buffer that
 * two callers disagree about how to cull.
 *
 * NO PERSISTENT WORLD MESH. Both buffers are allocated ONCE (here, at
 * renderer_init) and REBUILT FROM SCRATCH every renderer_draw_ground /
 * renderer_draw_vehicle call -- never a whole-world mesh, per this project's
 * "do not allocate a heightfield mesh for the whole world" hard constraint.
 * renderer_draw_ground only ever samples a RENDERER_GROUND_HALF_EXTENT-metre
 * patch around whatever `focus` it's given this call.
 * ------------------------------------------------------------------- */
typedef struct RenderVertex {
    float pos[4]; /* x, y, z, 1.0 -- matches dirt2.v.pica's v0/inpos */
    float col[4]; /* r, g, b, a, already 0..1 -- matches v1/inclr    */
} RenderVertex;

/* Ground patch sizing: a (2*HALF_EXTENT)^2 metre square, sampled every
 * CELL_SIZE metres, centred on `focus`. At HALF_EXTENT=16 / CELL_SIZE=1 that
 * is a 33x33 grid of sample points (1089 testground_query calls/frame -- a
 * handful of sines each, trivial next to a 120 Hz physics step) forming
 * SEGMENTS*SEGMENTS = 1024 quads. Each quad is 2 triangles of 3
 * (non-indexed, matching debugdraw.c's own non-indexed convention) verts =
 * 6 verts/quad, so RENDERER_GROUND_MAX_VERTS = 1024*6 = 6144 verts, i.e.
 * 6144 * sizeof(RenderVertex) = 6144*32 = 196608 bytes (192 KB) allocated
 * ONCE in linear memory -- a small slice of Old 3DS's ~64-80 MB app RAM, and
 * nowhere near the "whole world" (the testground's Z run is 140 m, far
 * beyond this 32 m-wide patch). 16 m half-extent comfortably covers what a
 * 55-degree-FOV chase camera (see DIRT2_FOV_DEGREES above) can actually see
 * at Phase 1's car-and-test-track scale. */
#define RENDERER_GROUND_HALF_EXTENT 16.0f
#define RENDERER_GROUND_CELL_SIZE   1.0f
#define RENDERER_GROUND_SEGMENTS    32
#define RENDERER_GROUND_GRID_POINTS (RENDERER_GROUND_SEGMENTS + 1)
#define RENDERER_GROUND_MAX_VERTS \
    (RENDERER_GROUND_SEGMENTS * RENDERER_GROUND_SEGMENTS * 6)

static RenderVertex *s_ground_verts = NULL;
static int s_ground_vert_count = 0;

/* Vehicle box sizing (metres, half-extents in BODY space: x forward, y up,
 * z right -- see core/rigidbody.h's header note on this project's body-axis
 * convention). Placeholder numbers for "a box for the car" until real car
 * art/dimensions exist -- nothing in vehicle_params.h specifies visual
 * chassis dimensions yet, so these are owned entirely by render, not read
 * from anywhere. */
/* HALF_Z MUST STAY BELOW THE WHEEL TRACK. main.c mounts the wheels at
 * z = +-0.8; the first version of this box was 0.85 half-width, so the body
 * was WIDER than the track and swallowed all four wheels whole. The first
 * Azahar boot that rendered anything at all showed a plain red brick with two
 * black slivers barely poking out of its side. 0.70 leaves 10 cm of each
 * wheel proud of the bodywork, which is what makes suspension travel
 * something you can see rather than something you infer.
 *
 * CENTER_Y offsets the box UP from the chassis origin, which is the centre of
 * MASS -- not the centre of the visible body. At half_y 0.45 and no offset
 * the box straddled the CoM (0.466 m when settled, see main.c) and its
 * underside sat below the ground plane. +0.30 puts the body's underside at
 * ~0.32 m with its roof at ~1.22 m, sitting on top of the wheels instead of
 * through them. */
#define RENDERER_CHASSIS_HALF_X  1.90f /* half-length, forward/back   */
#define RENDERER_CHASSIS_HALF_Y  0.45f /* half-height                 */
#define RENDERER_CHASSIS_HALF_Z  0.70f /* half-width, left/right      */
#define RENDERER_CHASSIS_CENTER_Y 0.30f /* body-space lift above the CoM */
#define RENDERER_WHEEL_HALF_X   0.30f /* wheel radius, in the plane containing forward+up */
#define RENDERER_WHEEL_HALF_Y   0.30f /* wheel radius, in the plane containing forward+up */
#define RENDERER_WHEEL_HALF_Z   0.12f /* half-width, along the spin axis (right) */

/* Chassis + 4 wheels, 6 faces/box, 2 triangles (6 verts, non-indexed) per
 * face -- 5*6*6 = 180 verts, 180*32 = 5760 bytes, allocated once. */
#define RENDERER_VEHICLE_MAX_BOXES 5
#define RENDERER_VEHICLE_MAX_VERTS (RENDERER_VEHICLE_MAX_BOXES * 6 * 6)

static RenderVertex *s_vehicle_verts = NULL;
static int s_vehicle_vert_count = 0;

/* Lambert ambient floor: how dark a face pointing away from
 * GROUND_LIGHT_DIR/vehicle's light is allowed to get, so a shaded box or
 * ground patch never goes fully black -- there is no real lighting system
 * yet (see this function group's header note), just enough shading for
 * shapes to read as three-dimensional rather than flat silhouettes. */
#define RENDERER_LIGHT_AMBIENT 0.25f

/* Track ribbon sizing: one segment per waypoint (segment i runs
 * waypoints[i] -> waypoints[(i+1)%count], see track.h), 2 triangles (6
 * non-indexed verts) per segment -- TRACK_MAX_WAYPOINTS*6 = 64*6 = 384 verts,
 * 384*32 = 12288 bytes, allocated once. Sized from TRACK_MAX_WAYPOINTS
 * (race/track.h) rather than a hand-typed number so a full 64-waypoint track
 * cannot overflow this buffer -- renderer_draw_track additionally clamps its
 * own loop count to TRACK_MAX_WAYPOINTS as a second, cheap backstop. */
#define RENDERER_TRACK_MAX_VERTS (TRACK_MAX_WAYPOINTS * 6)

/* Vertical lift applied to every ribbon vertex above the queried ground
 * height, so the track surface does not z-fight with the terrain patch
 * renderer_draw_ground draws at the same X/Z. 3 cm: comfortably above
 * anything a float height sample plus GEQUAL depth test could tie on, but a
 * small fraction (1/5) of the 0.15 m suspension travel the car's wheels
 * already move through, so the ribbon reads as "this IS the ground here",
 * not as a raised curb the car would visibly step up onto. */
#define RENDERER_TRACK_SURFACE_LIFT 0.03f

/* Length of the start/finish band along the track, in metres. 3 m is about
 * one car length (this chassis is 2.55 m between axles), which is what makes
 * it read as a line painted across the road rather than as a differently
 * surfaced stretch of it. */
#define RENDERER_TRACK_START_LINE_METRES 3.0f

static RenderVertex *s_track_verts = NULL;
static int s_track_vert_count = 0;
#endif /* __3DS__ */

void renderer_init(void) {
#ifdef __3DS__
    if (s_ready) return; /* one-time init only, see file header */

    C3D_Init(C3D_DEFAULT_CMDBUF_SIZE);

    s_target = C3D_RenderTargetCreate(TOP_SCREEN_WIDTH, TOP_SCREEN_HEIGHT,
                                       GPU_RB_RGBA8, GPU_RB_DEPTH24_STENCIL8);
    C3D_RenderTargetSetOutput(s_target, GFX_TOP, GFX_LEFT, DISPLAY_TRANSFER_FLAGS);
    C3D_SetViewport(0, 0, TOP_SCREEN_WIDTH, TOP_SCREEN_HEIGHT);

    s_dvlb = DVLB_ParseFile((u32 *)dirt2_shbin, dirt2_shbin_size);
    shaderProgramInit(&s_shader);
    shaderProgramSetVsh(&s_shader, &s_dvlb->DVLE[0]);
    C3D_BindProgram(&s_shader);

    s_uloc_projection = shaderInstanceGetUniformLocation(s_shader.vertexShader, "projection");
    s_uloc_modelview  = shaderInstanceGetUniformLocation(s_shader.vertexShader, "modelView");

    /* GPU_GEOMETRY_PRIM is not used (no geometry shader stage in dirt2.v.pica
     * -- Phase 1 draws triangles only). Depth test uses GEQUAL because
     * citro3d's Mtx_Persp/Mtx_PerspTilt produce a reversed depth range on
     * the PICA200 (near = 1.0, far = 0.0), matching both sibling projects'
     * and every standard devkitPro citro3d example's convention. */
    C3D_DepthTest(true, GPU_GEQUAL, GPU_WRITE_ALL);
    /* Debug lines/boxes are camera-agnostic ribbons (see debugdraw.c) with
     * no consistent winding once extruded, so culling stays off for now --
     * Phase 1 has no other 3D geometry yet (see main.c's TODO) to need it. */
    C3D_CullFace(GPU_CULL_NONE);
    C3D_AlphaBlend(GPU_BLEND_ADD, GPU_BLEND_ADD,
                   GPU_SRC_ALPHA, GPU_ONE_MINUS_SRC_ALPHA,
                   GPU_SRC_ALPHA, GPU_ONE_MINUS_SRC_ALPHA);

    /* Projection is fixed (FOV/aspect/near/far never change at runtime), so
     * it is built and uploaded exactly once here, not every frame; only the
     * view (uploaded as "modelView", see dirt2.v.pica) changes per frame
     * with the camera. */
    Mtx_PerspTilt(&s_projection, C3D_AngleFromDegrees(DIRT2_FOV_DEGREES),
                  C3D_AspectRatioTop, DIRT2_NEAR_CLIP, DIRT2_FAR_CLIP, false);
    C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_projection, &s_projection);

    C2D_Init(C2D_DEFAULT_MAX_OBJECTS);

    /* v0.1 gameplay-geometry buffers -- see their declaration above for the
     * sizing reasoning. Allocated once here, freed once in
     * renderer_shutdown, never per-frame or per-draw-call (same "one linear
     * allocation, cursor reset per frame" policy as debugdraw.c's s_verts).
     * A NULL result (out of linear memory) is handled at the draw-call sites
     * below (renderer_draw_ground/renderer_draw_vehicle no-op if their
     * buffer is NULL) rather than failing renderer_init itself -- the rest
     * of the renderer (debugdraw, the GPU frame bracket) stays usable even
     * if one of these allocations somehow failed. */
    s_ground_verts = (RenderVertex *)linearAlloc(RENDERER_GROUND_MAX_VERTS * sizeof(RenderVertex));
    s_vehicle_verts = (RenderVertex *)linearAlloc(RENDERER_VEHICLE_MAX_VERTS * sizeof(RenderVertex));
    s_track_verts = (RenderVertex *)linearAlloc(RENDERER_TRACK_MAX_VERTS * sizeof(RenderVertex));

    s_ready = true;
#endif
}

void renderer_shutdown(void) {
#ifdef __3DS__
    if (!s_ready) return;

    if (s_track_verts) {
        linearFree(s_track_verts);
        s_track_verts = NULL;
    }
    if (s_vehicle_verts) {
        linearFree(s_vehicle_verts);
        s_vehicle_verts = NULL;
    }
    if (s_ground_verts) {
        linearFree(s_ground_verts);
        s_ground_verts = NULL;
    }

    C2D_Fini();

    shaderProgramFree(&s_shader);
    if (s_dvlb) {
        DVLB_Free(s_dvlb);
        s_dvlb = NULL;
    }

    if (s_target) {
        C3D_RenderTargetDelete(s_target);
        s_target = NULL;
    }

    C3D_Fini();
    s_ready = false;
#endif
}

void renderer_frame_begin(const Camera *cam) {
#ifdef __3DS__
    if (!s_ready || !cam) return;

    C3D_Mtx view;
    Mtx_LookAt(&view,
               FVec3_New(cam->position.x, cam->position.y, cam->position.z),
               FVec3_New(cam->target.x, cam->target.y, cam->target.z),
               FVec3_New(0.0f, 1.0f, 0.0f), /* world up, see camera.c */
               false);

    C3D_FrameBegin(C3D_FRAME_SYNCDRAW); /* the real GPU wait -- see file
        header; C3D_FrameSync alone only waits for VBLANK. */
    C3D_RenderTargetClear(s_target, C3D_CLEAR_ALL, DIRT2_CLEAR_COLOR, 0);
    C3D_FrameDrawOn(s_target);

    /* REBIND THE 3D PROGRAM AND RE-UPLOAD BOTH UNIFORMS, EVERY FRAME.
     *
     * This is not defensive tidying, it is the fix for a total 3D blackout.
     * The first version of this file bound s_shader exactly once, in
     * renderer_init, and uploaded `projection` there as a one-off "it never
     * changes" optimisation. Two things then bind citro2d's OWN shader
     * program over it and never put it back:
     *   1. C2D_Init(), called LATER in renderer_init than C3D_BindProgram,
     *      so the very first frame was already drawing against the wrong
     *      program; and
     *   2. C2D_Prepare(), which debugdraw_frame_end calls every frame for
     *      its text pass (see debugdraw.c's own note that C2D_Prepare
     *      clobbers citro3d state).
     * PICA float uniforms live in the vertex shader's register file, so
     * writing s_uloc_projection/s_uloc_modelview while citro2d's program is
     * bound writes citro2d's registers, not ours. The observable symptom is
     * exactly what a boot in Azahar showed: 60 FPS, correct dt/steps/alpha
     * text, and not one pixel of ground, car or debug marker -- the 2D text
     * being the only thing drawn by the program that was actually bound.
     *
     * The depth test goes back too. C2D_Prepare sets its own, so the
     * GPU_GEQUAL/GPU_WRITE_ALL configured in renderer_init survives only
     * until debugdraw's first text pass. Cull and blend are re-set by each
     * draw call already; these two are not. */
    C3D_BindProgram(&s_shader);
    C3D_DepthTest(true, GPU_GEQUAL, GPU_WRITE_ALL);
    C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_projection, &s_projection);
    C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_modelview, &view);
#else
    (void)cam;
#endif
}

void renderer_frame_end(void) {
#ifdef __3DS__
    if (!s_ready) return;
    C3D_FrameEnd(0);
#endif
}

#ifdef __3DS__
/* Per-zone base colour for the ground mesh, straight from testground.h's own
 * zone layout doc (flat / rolling hills / washboard, in that order along
 * +Z) -- this is deliberately a cheap visual aid for verification (per this
 * project's "make it visible, don't just reason about it" discipline), not
 * real surface art: a driver crossing from zone to zone should be able to
 * SEE the transition, not just feel a suspension change. */
static Vec3 ground_zone_color(const Testground *tg, f32 world_z) {
    const TestgroundConfig *cfg = &tg->config;
    if (world_z < cfg->flat_length) {
        return vec3_make(0.45f, 0.50f, 0.35f); /* zone 1: flat, muted green-grey */
    } else if (world_z < cfg->flat_length + cfg->hills_length) {
        return vec3_make(0.30f, 0.55f, 0.25f); /* zone 2: rolling hills, green   */
    } else {
        return vec3_make(0.55f, 0.45f, 0.30f); /* zone 3: washboard, tan/dirt    */
    }
}

static void ground_push_vertex(Vec3 pos, Vec3 color) {
    RenderVertex *v = &s_ground_verts[s_ground_vert_count];
    v->pos[0] = pos.x; v->pos[1] = pos.y; v->pos[2] = pos.z; v->pos[3] = 1.0f;
    v->col[0] = color.x; v->col[1] = color.y; v->col[2] = color.z; v->col[3] = 1.0f;
    s_ground_vert_count++;
}
#endif /* __3DS__ */

void renderer_draw_ground(const Testground *tg, Vec3 focus) {
#ifdef __3DS__
    /* Per-grid-point sample: height/normal-derived shaded colour, computed
     * ONCE per point here and reused by every quad that shares it (each
     * interior point is a corner of up to 4 quads) rather than
     * re-querying/re-shading per triangle. `static` so this is BSS, not
     * ~35 KB of physics-adjacent stack. */
    static Vec3 s_grid_pos[RENDERER_GROUND_GRID_POINTS * RENDERER_GROUND_GRID_POINTS];
    static Vec3 s_grid_color[RENDERER_GROUND_GRID_POINTS * RENDERER_GROUND_GRID_POINTS];
    static bool s_grid_valid[RENDERER_GROUND_GRID_POINTS * RENDERER_GROUND_GRID_POINTS];
    int i, j;

    if (!s_ready || !s_ground_verts || !tg) return;

    Vec3 light_dir = vec3_normalize(vec3_make(0.3f, 0.85f, 0.35f)); /* fixed
        "sun", mostly overhead -- see RENDERER_LIGHT_AMBIENT's comment, there
        is no real lighting system yet. */
    f32 origin_x = focus.x - RENDERER_GROUND_HALF_EXTENT;
    f32 origin_z = focus.z - RENDERER_GROUND_HALF_EXTENT;

    for (j = 0; j < RENDERER_GROUND_GRID_POINTS; j++) {
        for (i = 0; i < RENDERER_GROUND_GRID_POINTS; i++) {
            int idx = j * RENDERER_GROUND_GRID_POINTS + i;
            f32 wx = origin_x + (f32)i * RENDERER_GROUND_CELL_SIZE;
            f32 wz = origin_z + (f32)j * RENDERER_GROUND_CELL_SIZE;
            f32 h;
            Vec3 n;
            bool ok = testground_query(tg, wx, wz, &h, &n);
            s_grid_valid[idx] = ok;
            if (ok) {
                f32 lit = vec3_dot(n, light_dir);
                if (lit < RENDERER_LIGHT_AMBIENT) lit = RENDERER_LIGHT_AMBIENT;
                if (lit > 1.0f) lit = 1.0f;
                s_grid_pos[idx] = vec3_make(wx, h, wz);
                s_grid_color[idx] = vec3_scale(ground_zone_color(tg, wz), lit);
            }
        }
    }

    s_ground_vert_count = 0;
    for (j = 0; j < RENDERER_GROUND_SEGMENTS; j++) {
        bool budget_hit = false;
        for (i = 0; i < RENDERER_GROUND_SEGMENTS; i++) {
            int i00 = j * RENDERER_GROUND_GRID_POINTS + i;
            int i10 = j * RENDERER_GROUND_GRID_POINTS + (i + 1);
            int i01 = (j + 1) * RENDERER_GROUND_GRID_POINTS + i;
            int i11 = (j + 1) * RENDERER_GROUND_GRID_POINTS + (i + 1);

            if (!s_grid_valid[i00] || !s_grid_valid[i10] ||
                !s_grid_valid[i01] || !s_grid_valid[i11])
                continue; /* a corner is off the heightfield -- see
                    testground.h's "out of bounds is no ground, not
                    extrapolated" contract; skip the whole quad rather than
                    guess a height for the missing corner. */

            if (s_ground_vert_count + 6 > RENDERER_GROUND_MAX_VERTS) {
                budget_hit = true; /* unreachable given this buffer's sizing
                    (see its declaration), but fail closed -- stop emitting
                    rather than overrun, same policy as debugdraw.c. */
                break;
            }

            /* Two triangles per quad, (c00,c01,c10) then (c10,c01,c11) --
             * CCW as seen from above (+Y), matching GPU_CULL_BACK_CCW below.
             * Derivation: with edges e1 = +Z, e2 = +X, e1 x e2 = +Y (the
             * right-handed identity Z x X = Y), so winding v0,(v0+Z),(v0+X)
             * is front-facing for a normal pointing up; the second triangle
             * covering the same quad's other half was verified against the
             * same identity by hand before writing this loop. */
            ground_push_vertex(s_grid_pos[i00], s_grid_color[i00]);
            ground_push_vertex(s_grid_pos[i01], s_grid_color[i01]);
            ground_push_vertex(s_grid_pos[i10], s_grid_color[i10]);

            ground_push_vertex(s_grid_pos[i10], s_grid_color[i10]);
            ground_push_vertex(s_grid_pos[i01], s_grid_color[i01]);
            ground_push_vertex(s_grid_pos[i11], s_grid_color[i11]);
        }
        if (budget_hit) break;
    }

    if (s_ground_vert_count > 0) {
        C3D_AttrInfo *attr = C3D_GetAttrInfo();
        AttrInfo_Init(attr);
        AttrInfo_AddLoader(attr, 0, GPU_FLOAT, 4); /* position */
        AttrInfo_AddLoader(attr, 1, GPU_FLOAT, 4); /* colour   */

        C3D_BufInfo *buf = C3D_GetBufInfo();
        BufInfo_Init(buf);
        BufInfo_Add(buf, s_ground_verts, sizeof(RenderVertex), 2, 0x10);

        C3D_TexEnv *env = C3D_GetTexEnv(0);
        C3D_TexEnvInit(env);
        C3D_TexEnvSrc(env, C3D_Both, GPU_PRIMARY_COLOR, GPU_PRIMARY_COLOR, GPU_PRIMARY_COLOR);
        C3D_TexEnvFunc(env, C3D_Both, GPU_REPLACE);

        /* Real geometry with correctly-wound triangles, unlike debugdraw's
         * camera-agnostic ribbons -- cull backfaces, then restore
         * GPU_CULL_NONE so debugdraw's own later draw this frame (which
         * relies on that baseline, see its header comment) keeps working
         * unchanged. */
        C3D_CullFace(GPU_CULL_BACK_CCW);
        GSPGPU_FlushDataCache(s_ground_verts, (u32)(s_ground_vert_count * sizeof(RenderVertex)));
        C3D_DrawArrays(GPU_TRIANGLES, 0, s_ground_vert_count);
        C3D_CullFace(GPU_CULL_NONE);
    }
#else
    (void)tg; (void)focus;
#endif
}

#ifdef __3DS__
static void vehicle_push_vertex(Vec3 pos, Vec3 color) {
    RenderVertex *v = &s_vehicle_verts[s_vehicle_vert_count];
    v->pos[0] = pos.x; v->pos[1] = pos.y; v->pos[2] = pos.z; v->pos[3] = 1.0f;
    v->col[0] = color.x; v->col[1] = color.y; v->col[2] = color.z; v->col[3] = 1.0f;
    s_vehicle_vert_count++;
}

/* Pushes one shaded box (chassis or a wheel) into s_vehicle_verts, oriented
 * by `orient` and centred at `center`, in BODY-space half_extents (x
 * forward, y up, z right -- core/rigidbody.h's convention).
 *
 * FACE_CORNERS/FACE_LOCAL_NORMAL winding derivation: corners are indexed
 * 0..7 by the same bit convention as debugdraw_wire_box (debugdraw.c) --
 * bit0 selects +/-x, bit1 +/-y, bit2 +/-z (so e.g. corner 1 = (+x,-y,-z),
 * corner 7 = (+x,+y,+z)). For each face, the 4 corner indices are listed in
 * an order such that the fan (v0,v1,v2) + (v0,v2,v3) is front-facing under
 * GPU_CULL_BACK_CCW -- each row was checked by plugging its actual
 * (v1-v0) x (v2-v0) into the outward axis it claims before being written
 * down here. E.g. +X = {1,3,7,5}: v0=corner1=(x,-y,-z), v1=corner3=(x,y,-z),
 * v2=corner7=(x,y,z); (v1-v0)=(0,2y,0), (v2-v0)=(0,2y,2z), and their cross
 * product is (4yz,0,0) -- positive X, matching the +X face it's meant to be.
 * The other five rows were each checked the same way. Rotating each face's
 * LOCAL outward normal by the same `orient` used for the corners gives the
 * correct WORLD outward normal because `orient` is a pure
 * (handedness-preserving) rotation -- no separate normal-matrix needed for
 * a uniform-scale box like this. */
static void push_box(Vec3 center, Vec3 half_extents, Quat orient,
                      Vec3 base_color, Vec3 light_dir) {
    static const int FACE_CORNERS[6][4] = {
        { 1, 3, 7, 5 }, /* +X */
        { 0, 4, 6, 2 }, /* -X */
        { 2, 6, 7, 3 }, /* +Y */
        { 0, 1, 5, 4 }, /* -Y */
        { 4, 5, 7, 6 }, /* +Z */
        { 0, 2, 3, 1 }, /* -Z */
    };
    static const Vec3 FACE_LOCAL_NORMAL[6] = {
        {  1.0f,  0.0f,  0.0f }, { -1.0f,  0.0f,  0.0f },
        {  0.0f,  1.0f,  0.0f }, {  0.0f, -1.0f,  0.0f },
        {  0.0f,  0.0f,  1.0f }, {  0.0f,  0.0f, -1.0f },
    };
    Vec3 local[8], world[8];
    int k, f;

    for (k = 0; k < 8; k++) {
        local[k] = vec3_make(
            (k & 1) ? half_extents.x : -half_extents.x,
            (k & 2) ? half_extents.y : -half_extents.y,
            (k & 4) ? half_extents.z : -half_extents.z);
        world[k] = vec3_add(center, vec3_rotate_by_quat(local[k], orient));
    }

    for (f = 0; f < 6; f++) {
        Vec3 world_normal, shaded, a, b, c, d;
        f32 lit;

        if (s_vehicle_vert_count + 6 > RENDERER_VEHICLE_MAX_VERTS) return; /*
            over budget -- unreachable at this file's fixed 5-box/frame
            usage (see RENDERER_VEHICLE_MAX_VERTS), fail closed regardless. */

        world_normal = vec3_rotate_by_quat(FACE_LOCAL_NORMAL[f], orient);
        lit = vec3_dot(world_normal, light_dir);
        if (lit < RENDERER_LIGHT_AMBIENT) lit = RENDERER_LIGHT_AMBIENT;
        if (lit > 1.0f) lit = 1.0f;
        shaded = vec3_scale(base_color, lit);

        a = world[FACE_CORNERS[f][0]];
        b = world[FACE_CORNERS[f][1]];
        c = world[FACE_CORNERS[f][2]];
        d = world[FACE_CORNERS[f][3]];

        vehicle_push_vertex(a, shaded);
        vehicle_push_vertex(b, shaded);
        vehicle_push_vertex(c, shaded);

        vehicle_push_vertex(a, shaded);
        vehicle_push_vertex(c, shaded);
        vehicle_push_vertex(d, shaded);
    }
}
#endif /* __3DS__ */

void renderer_draw_vehicle(Vec3 chassis_pos, Quat chassis_orient,
                            const Vec3 wheel_local_offsets[VEHICLE_WHEEL_COUNT]) {
#ifdef __3DS__
    int i;

    if (!s_ready || !s_vehicle_verts) return;

    Vec3 light_dir = vec3_normalize(vec3_make(0.3f, 0.85f, 0.35f));
    Vec3 chassis_half = vec3_make(RENDERER_CHASSIS_HALF_X, RENDERER_CHASSIS_HALF_Y, RENDERER_CHASSIS_HALF_Z);
    Vec3 wheel_half = vec3_make(RENDERER_WHEEL_HALF_X, RENDERER_WHEEL_HALF_Y, RENDERER_WHEEL_HALF_Z);
    Vec3 chassis_color = vec3_make(0.70f, 0.12f, 0.12f); /* placeholder red -- no real car art yet */
    Vec3 wheel_color = vec3_make(0.08f, 0.08f, 0.08f);   /* placeholder near-black */

    s_vehicle_vert_count = 0;

    /* The body box is lifted along the chassis's OWN up axis, not world +Y,
     * so it stays planted on the car when the car pitches or rolls. */
    push_box(vec3_add(chassis_pos,
                      vec3_rotate_by_quat(vec3_make(0.0f, RENDERER_CHASSIS_CENTER_Y, 0.0f),
                                          chassis_orient)),
             chassis_half, chassis_orient, chassis_color, light_dir);
    for (i = 0; i < VEHICLE_WHEEL_COUNT; i++) {
        Vec3 wheel_center = vec3_add(chassis_pos,
            vec3_rotate_by_quat(wheel_local_offsets[i], chassis_orient));
        push_box(wheel_center, wheel_half, chassis_orient, wheel_color, light_dir);
    }

    if (s_vehicle_vert_count > 0) {
        C3D_AttrInfo *attr = C3D_GetAttrInfo();
        AttrInfo_Init(attr);
        AttrInfo_AddLoader(attr, 0, GPU_FLOAT, 4); /* position */
        AttrInfo_AddLoader(attr, 1, GPU_FLOAT, 4); /* colour   */

        C3D_BufInfo *buf = C3D_GetBufInfo();
        BufInfo_Init(buf);
        BufInfo_Add(buf, s_vehicle_verts, sizeof(RenderVertex), 2, 0x10);

        C3D_TexEnv *env = C3D_GetTexEnv(0);
        C3D_TexEnvInit(env);
        C3D_TexEnvSrc(env, C3D_Both, GPU_PRIMARY_COLOR, GPU_PRIMARY_COLOR, GPU_PRIMARY_COLOR);
        C3D_TexEnvFunc(env, C3D_Both, GPU_REPLACE);

        C3D_CullFace(GPU_CULL_BACK_CCW); /* see renderer_draw_ground's identical
            bracket -- restored to GPU_CULL_NONE below for debugdraw's sake. */
        GSPGPU_FlushDataCache(s_vehicle_verts, (u32)(s_vehicle_vert_count * sizeof(RenderVertex)));
        C3D_DrawArrays(GPU_TRIANGLES, 0, s_vehicle_vert_count);
        C3D_CullFace(GPU_CULL_NONE);
    }
#else
    (void)chassis_pos; (void)chassis_orient; (void)wheel_local_offsets;
#endif
}

#ifdef __3DS__
static void track_push_vertex(Vec3 pos, Vec3 color) {
    RenderVertex *v = &s_track_verts[s_track_vert_count];
    v->pos[0] = pos.x; v->pos[1] = pos.y; v->pos[2] = pos.z; v->pos[3] = 1.0f;
    v->col[0] = color.x; v->col[1] = color.y; v->col[2] = color.z; v->col[3] = 1.0f;
    s_track_vert_count++;
}

/* Dirt/gravel grey-brown for the ordinary racing surface -- distinct in hue
 * (flatter, greyer) from every ground_zone_color band (all three of which
 * lean green or tan), so the track reads as a different material rather than
 * another terrain zone. Owned entirely by this file, not a supplied asset. */
static const Vec3 RENDERER_TRACK_SURFACE_COLOR = { 0.42f, 0.40f, 0.37f };

/* Bright near-white band for the waypoints[0]->waypoints[1] segment -- the
 * start/finish line (see renderer.h's header comment on renderer_draw_track)
 * -- unmistakably different from both the dirt ribbon and the terrain. */
static const Vec3 RENDERER_TRACK_START_COLOR = { 0.95f, 0.95f, 0.95f };
#endif /* __3DS__ */

void renderer_draw_track(const Testground *tg, const Track *track) {
#ifdef __3DS__
    /* One left/right ribbon-edge vertex per waypoint, computed ONCE and
     * shared by the two quads that meet there (this waypoint's outgoing
     * segment and the previous waypoint's segment) -- same "compute once per
     * shared point, duplicate into the non-indexed vertex buffer per quad"
     * policy as renderer_draw_ground's s_grid_pos/s_grid_color. `static` so
     * this is BSS, not stack. */
    static Vec3 s_edge_left[TRACK_MAX_WAYPOINTS];
    static Vec3 s_edge_right[TRACK_MAX_WAYPOINTS];
    static bool s_edge_valid[TRACK_MAX_WAYPOINTS];
    int i, count;

    if (!s_ready || !s_track_verts || !tg || !track) return;

    count = track->count;
    if (count > TRACK_MAX_WAYPOINTS) count = TRACK_MAX_WAYPOINTS; /* fail
        closed against a corrupt/oversized Track rather than reading past
        s_edge_left/s_edge_right/s_edge_valid -- track_init's own contract
        already caps count at TRACK_MAX_WAYPOINTS, this is a second, cheap
        backstop (see requirement in renderer.h/the task brief). */
    if (count < 3) return; /* not a loop, nothing to draw */

    for (i = 0; i < count; i++) {
        int prev = (i - 1 + count) % count;
        int next = (i + 1) % count;
        Vec3 to_here = vec3_sub(track->waypoints[i].center, track->waypoints[prev].center);
        Vec3 to_next = vec3_sub(track->waypoints[next].center, track->waypoints[i].center);
        Vec3 dir_in, dir_out, tangent, left_dir;
        f32 wx_l, wz_l, wx_r, wz_r, h_l, h_r;
        Vec3 n_unused;
        bool ok_l, ok_r;

        /* XZ-plane direction only -- track.h's file header is explicit that
         * every query in this module ignores Y entirely; this isn't a
         * track_query call, but the ribbon's edge offsets are a ground-plan
         * (X/Z) construction in exactly the same sense, so the same rule
         * applies to the tangent computed here. */
        to_here.y = 0.0f;
        to_next.y = 0.0f;
        dir_in = vec3_normalize(to_here);
        dir_out = vec3_normalize(to_next);
        tangent = vec3_normalize(vec3_add(dir_in, dir_out));
        if (vec3_length_sq(tangent) < 1e-8f) tangent = dir_out; /* dir_in and
            dir_out exactly cancel (a zero-radius hairpin) -- fall back to
            the outgoing direction rather than keep a zero-length tangent. */

        /* Perpendicular to `tangent` in the XZ plane, rotated so that
         * cross(tangent, left_dir) has a POSITIVE y component -- the same
         * "positive is to the LEFT of the driving direction" convention
         * TrackQueryResult.lateral_offset documents (track.h), so this
         * ribbon's "left" matches what the rest of the race code already
         * calls left. Derivation: for tangent=(tx,0,tz), left_dir=(-tz,0,tx)
         * is perpendicular (dot = tx*-tz + tz*tx = 0) and, using vec3_cross's
         * definition, cross(tangent,left_dir).y = tx*tx - tz*(-tz) =
         * tx^2+tz^2 = 1 for a unit tangent -- positive, as required. */
        left_dir = vec3_make(-tangent.z, 0.0f, tangent.x);

        wx_l = track->waypoints[i].center.x + left_dir.x * track->waypoints[i].half_width;
        wz_l = track->waypoints[i].center.z + left_dir.z * track->waypoints[i].half_width;
        wx_r = track->waypoints[i].center.x - left_dir.x * track->waypoints[i].half_width;
        wz_r = track->waypoints[i].center.z - left_dir.z * track->waypoints[i].half_width;

        /* Ground height, NOT track->waypoints[i].center.y -- see track.h's
         * file header ("a track waypoint's Y is not read by any query
         * here... the world's own height query is the only source of truth
         * for ground height") and renderer_draw_ground's identical use of
         * testground_query for the terrain patch this ribbon sits on top of. */
        ok_l = testground_query(tg, wx_l, wz_l, &h_l, &n_unused);
        ok_r = testground_query(tg, wx_r, wz_r, &h_r, &n_unused);
        s_edge_valid[i] = ok_l && ok_r;
        if (s_edge_valid[i]) {
            s_edge_left[i]  = vec3_make(wx_l, h_l + RENDERER_TRACK_SURFACE_LIFT, wz_l);
            s_edge_right[i] = vec3_make(wx_r, h_r + RENDERER_TRACK_SURFACE_LIFT, wz_r);
        }
    }

    s_track_vert_count = 0;
    for (i = 0; i < count; i++) {
        int next = (i + 1) % count;
        Vec3 r0, r1, l0, l1, color;

        if (!s_edge_valid[i] || !s_edge_valid[next])
            continue; /* an edge is off the heightfield -- skip the whole
                quad rather than guess a height for the missing corner, same
                policy as renderer_draw_ground. */

        if (s_track_vert_count + 6 > RENDERER_TRACK_MAX_VERTS)
            break; /* unreachable given this buffer's TRACK_MAX_WAYPOINTS*6
                sizing (see its declaration) -- fail closed regardless. */

        r0 = s_edge_right[i];
        r1 = s_edge_right[next];
        l0 = s_edge_left[i];
        l1 = s_edge_left[next];

        /* Every segment is the same dirt/gravel colour. The start/finish
         * marking is NOT a coloured segment -- see the separate band emitted
         * after this loop and the comment there for why. */
        color = RENDERER_TRACK_SURFACE_COLOR;

        /* WINDING, and this was wrong once. The first version emitted
         * (r0,r1,l0) + (l0,r1,l1), reasoning by analogy with
         * renderer_draw_ground's index pattern. On hardware that produced a
         * completely invisible track: every triangle was back-facing and
         * GPU_CULL_BACK_CCW removed all of them, which looks exactly like
         * "the draw call never ran" and cost a build to tell apart.
         *
         * Measured, not re-derived: with C3D_CullFace(GPU_CULL_NONE) the
         * whole ribbon rendered correctly in the same frame, which isolates
         * the fault to winding and nothing else -- not the vertex buffer, not
         * the height queries, not the depth test, not the attribute layout.
         *
         * The order below is the reverse of that, i.e. (r0,l0,r1) +
         * (l0,l1,r1), and is verified front-facing under GPU_CULL_BACK_CCW
         * by the capture that followed. */
        track_push_vertex(r0, color);
        track_push_vertex(l0, color);
        track_push_vertex(r1, color);

        track_push_vertex(l0, color);
        track_push_vertex(l1, color);
        track_push_vertex(r1, color);
    }

    /* ---- start/finish band ----
     * A SHORT band across the track at waypoint 0, not a recoloured segment.
     * Colouring segment 0 was the first attempt and it is wrong for this
     * circuit: waypoints[0] -> waypoints[1] is the entire 96 m left-hand
     * straight, so the "line" rendered as a 96-metre white road. A start line
     * has to be short enough to be a landmark; a segment's length is a
     * property of how the track was tessellated and has nothing to do with
     * that.
     *
     * RENDERER_TRACK_START_LINE_METRES along the segment, or the whole
     * segment if the segment is shorter than that -- a densely tessellated
     * track must not produce a band longer than the segment it sits on. */
    if (s_edge_valid[0] && s_edge_valid[1 % count] &&
        s_track_vert_count + 6 <= RENDERER_TRACK_MAX_VERTS) {
        int next = 1 % count;
        Vec3 l0 = s_edge_left[0],  l1 = s_edge_left[next];
        Vec3 r0 = s_edge_right[0], r1 = s_edge_right[next];
        f32 span = vec3_length(vec3_sub(l1, l0));
        f32 t = (span > RENDERER_TRACK_START_LINE_METRES)
                    ? (RENDERER_TRACK_START_LINE_METRES / span)
                    : 1.0f;
        /* Lifted again above the ribbon it sits on, for the same reason the
         * ribbon is lifted above the terrain: two coplanar surfaces at the
         * same height z-fight, and the loser flickers per pixel. */
        Vec3 up = vec3_make(0.0f, RENDERER_TRACK_SURFACE_LIFT * 0.5f, 0.0f);
        Vec3 bl = vec3_add(l0, up);
        Vec3 br = vec3_add(r0, up);
        Vec3 fl = vec3_add(vec3_lerp(l0, l1, t), up);
        Vec3 fr = vec3_add(vec3_lerp(r0, r1, t), up);

        track_push_vertex(br, RENDERER_TRACK_START_COLOR);
        track_push_vertex(bl, RENDERER_TRACK_START_COLOR);
        track_push_vertex(fr, RENDERER_TRACK_START_COLOR);

        track_push_vertex(bl, RENDERER_TRACK_START_COLOR);
        track_push_vertex(fl, RENDERER_TRACK_START_COLOR);
        track_push_vertex(fr, RENDERER_TRACK_START_COLOR);
    }

    if (s_track_vert_count > 0) {
        C3D_AttrInfo *attr = C3D_GetAttrInfo();
        AttrInfo_Init(attr);
        AttrInfo_AddLoader(attr, 0, GPU_FLOAT, 4); /* position */
        AttrInfo_AddLoader(attr, 1, GPU_FLOAT, 4); /* colour   */

        C3D_BufInfo *buf = C3D_GetBufInfo();
        BufInfo_Init(buf);
        BufInfo_Add(buf, s_track_verts, sizeof(RenderVertex), 2, 0x10);

        C3D_TexEnv *env = C3D_GetTexEnv(0);
        C3D_TexEnvInit(env);
        C3D_TexEnvSrc(env, C3D_Both, GPU_PRIMARY_COLOR, GPU_PRIMARY_COLOR, GPU_PRIMARY_COLOR);
        C3D_TexEnvFunc(env, C3D_Both, GPU_REPLACE);

        /* Real, correctly-wound geometry -- cull backfaces, then restore
         * GPU_CULL_NONE so debugdraw's own later draw this frame (which
         * relies on that baseline, see its header comment) keeps working
         * unchanged. Same bracket as renderer_draw_ground/renderer_draw_vehicle. */
        C3D_CullFace(GPU_CULL_BACK_CCW);
        GSPGPU_FlushDataCache(s_track_verts, (u32)(s_track_vert_count * sizeof(RenderVertex)));
        C3D_DrawArrays(GPU_TRIANGLES, 0, s_track_vert_count);
        C3D_CullFace(GPU_CULL_NONE);
    }
#else
    (void)tg; (void)track;
#endif
}

#ifdef __3DS__
C3D_RenderTarget *renderer_get_target(void) {
    return s_target;
}
#endif
