/* AUTO-GENERATED by gen_tyre_lut.py -- do not hand-edit. Rerun the
 * generator instead. Table size 256, rho range [0, 3.5].
 *
 * COPIED into this project from the offline LUT generator at
 * scratchpad/tyre_lut/ (see gen_tyre_lut.py / lut_builder.py / surfaces.py
 * / pacejka.py there for how the table data below was produced, and
 * arcade_tuning_rationale.txt for the per-surface tuning reasoning). This
 * copy is the project's own standalone source; nothing in dirt2 includes
 * or references the scratchpad path.
 *
 * ONE LOCAL CHANGE FROM THE GENERATOR OUTPUT: the per-surface params
 * struct below is named TyreLutSurfaceParams, not TyreSurfaceParams --
 * the generator's original name collides with vehicle/tyre.h's own
 * (differently-shaped) TyreSurfaceParams struct, which is this project's
 * existing public contract type and cannot be renamed. All table DATA
 * (g_tyre_lut, g_tyre_surface_params, both in tyre_lut.c) is untouched. */
#ifndef DIRT2_VEHICLE_TYRE_LUT_H
#define DIRT2_VEHICLE_TYRE_LUT_H

#ifdef __cplusplus
extern "C" {
#endif

#define TYRE_LUT_SIZE     256
#define TYRE_LUT_RHO_MAX  3.5f

typedef enum {
    TYRE_SURFACE_TARMAC_DRY,
    TYRE_SURFACE_TARMAC_WET,
    TYRE_SURFACE_HARDPACKED_DIRT,
    TYRE_SURFACE_GRAVEL,
    TYRE_SURFACE_SAND,
    TYRE_SURFACE_MUD,
    TYRE_SURFACE_GRASS,
    TYRE_SURFACE_SNOW,
    TYRE_SURFACE_COUNT
} TyreSurface;

typedef enum {
    TYRE_TUNING_BASELINE,
    TYRE_TUNING_ARCADE,
    TYRE_TUNING_COUNT
} TyreTuning;

typedef struct {
    float mu;              /* peak normalised force coefficient */
    float sr_peak;         /* slip ratio (fraction) at peak longitudinal force */
    float alpha_peak_deg;  /* slip angle (degrees) at peak lateral force */
} TyreLutSurfaceParams;

extern const TyreLutSurfaceParams g_tyre_surface_params[TYRE_SURFACE_COUNT];

/* Linear-interpolated lookup of the normalised force magnitude F(rho). */
float tyre_lut_lookup(TyreTuning tuning, TyreSurface surface, float rho);

/* rho = sqrt((sr/sr_peak)^2 + (alpha_deg/alpha_peak_deg)^2) */
float tyre_lut_rho(TyreSurface surface, float sr, float alpha_deg);

/* Splits a looked-up normalised force magnitude into (fx, fy) by the
 * direction of the slip vector in (sr/sr_peak, alpha/alpha_peak) space --
 * the friction-ellipse split. Never compute fx/fy independently and
 * rescale afterwards. */
void tyre_lut_split(TyreSurface surface, float sr, float alpha_deg,
                     float f_mag, float *fx, float *fy);

#ifdef __cplusplus
}
#endif

#endif /* TYRE_LUT_H */
